mattkirby/puppet-zpr

- manifests/job.pp
Without this change zpr will allow a job to be created that cannot be processed because the title contains whitespace characters. This commit adds a case statement in the zpr::job define type to determine whether the resource title contains whitespace. If it does then the compile will fail with an error reporting that there is whitespace in your resource title, and that this is not supported.
> Add a check whitespace in job title

- manifests/job.pp
Without this change the whitespace check using regex in the case statement for zpr job detects whitespace when none is present. This commit simplifies the regex remove the * to detect whitespace only.
> Fix regex to only match whitespace

- manifests/offsite.pp
- manifests/params.pp
- manifests/storage.pp
- manifests/worker.pp
Without this change zpr limits collection of exported resources to a specified environment. This commit makes this behavior more flexible by removing a default env_tag and limiting on env_tag if env_tag is set
> Only collect on environment if env_tag is set

- manifests/user.pp
With recent changes that allow for env_tag to be empty, the conditional
logic that all the collectors use was missing from the zpr::user
class. This adds the logic to that class as well.
> Update zpr::user to handle absent env_tag

- manifests/offsite.pp
- manifests/storage.pp
- manifests/user.pp
- manifests/worker.pp
Without this change there are unnecessary if statements used to declare
tags to be checked for collection in worker, storage and offsite
classes. Additionally, the ssh key for the worker user is not collected
unless the environment matches $env_tag. This commit moves tags into an array so that it may be
referenced as $tags and allow removal of the if statements. The
ssh_authorized_key resource for the zpr worker user is now collected
regardless of environment when a backup job is declared.
> Move tags into an array

- manifests/params.pp
- manifests/rsync.pp
This commit moves rsync commands into an array and uses join to combine
them. The result is that the code is kept more readable. Additionally,
in params the default user is set to the user variable.
> Move rsync commands into an array

- lib/facter/zpr_ssh_key.rb
- manifests/aws.pp
- manifests/backup_dir.pp
- manifests/duplicity.pp
- manifests/generate_ssh_key.pp
- manifests/gpg.pp
- manifests/job.pp
- manifests/offsite.pp
- manifests/rsync.pp
- manifests/storage.pp
- manifests/task_spooler.pp
- manifests/user.pp
- manifests/worker.pp
Without this change exclude_dir being set to undef prints undef in the
rsync command. The result is an invalid rsync command. The commit
changes the array so it only includes exclude_dir if exclude_dir is set.
Additionally, the zpr_ssh_key fact previously had a hardcoded directory
path. It now obtains that directory path from /etc/passwd using getpwnam
for zpr_proxy.
All manifests previously nested under resources have been placed at the
top scope, and references have been adjusted accordingly.
Duplicity command structure has been simplified and made easier to
adjust. There are now only two jobs created and the ability provided to
specify how frequently a full backup should be taken. This makes
scheduling full and incremental backups much easier as well since
duplicity will figure out …
> Fix exclude_dir

- README.md
- manifests/init.pp
- manifests/job.pp
- manifests/params.pp
- manifests/storage.pp
Without this change the schedule for snapshots is hidden from the user
and only run once daily. This is not helpful if you want your backups to
run more often.
Additionally, zpr::job was previously undocumented. This commit adds
documentation for zpr::job. Storage_tag is removed, and server is
replaced by storage.
A readme is updated for the module to provide far more detail.
> Expose cron schedule for snapshot and duplicity. Add docs

- manifests/generate_ssh_key.pp
- manifests/init.pp
- manifests/job.pp
- manifests/params.pp
- manifests/rsync_cmd.pp
- manifests/user.pp
- manifests/worker.pp
Without this change the sshkey type can cause unpredictable failures due
to its unreliable nature when dealing with large numbers of keys. Since
there are long standing bugs on this type not being addressed I have
opted to move to concat for management of known hosts instead. The file
resource for known_hosts is removed as a result.
Workers now set source user automatically since a worker without a
source user is not very useful. The parameter is removed from params as
a result.
The server parameter in job is replaced with storage, and storage_tag is
removed.
The rsync_cmd class is refactored to allow restricting a command to a
particular environment if desired and moves resource collection there
instead of the user class.
> Replace sshkey type with concat

- manifests/rsync.pp
- manifests/user.pp
- templates/ssh_forced_commands_wrapper.py.erb
This commit adds support for systems that do not have ecdsa keys. It
will default to a rsa key in that case in order to populate known hosts
on the worker node. Additionally, prior to this commit the rsync
command produced when exclude includes an array does not quote the
values produced. Lastly, support for squeeze is added to the wrapper
script since there is no python2 reference there.
> Support keys other than ecdsa. Fix exclude in rsync

- manifests/job.pp
- manifests/offsite.pp
- manifests/rsync.pp
- manifests/worker.pp
This commit replaces default rsync options to remove preserving access
times. Additionally, the i option is added to defaults to provide a
summary of what has changed in the output of each rsync job. Group
nobody is changed to nogroup for file management.
> Replace default rsync options to remove preserving access times.

- manifests/task_spooler.pp
Without this change taskspooler doesn't send the same spool as what is
configured in .tsprc. This commit ensures the values are the same.
> Ensure correct tsp output is sent to file

- manifests/task_spooler.pp
This commit fixes the reference to tsp_dir when printing tsp output to a
file. Without this change the correct socket will not be found and task
spooler output will be stale, or non-existent.
> Fix reference to tsp_dir

- manifests/duplicity.pp
- manifests/rsync.pp
This commit reformats the base duplicity command to ensure tsp vars are
loaded during duplicity tsp job. Without this change the duplicity job
does not show up in the correct tsp output.
> Reformat base command for duplicity

- manifests/job.pp
This commit moves the logic of a default read ip address out of zfs
share and into zpr job.
> Add default read ip logic to zpr job

- manifests/gpg.pp
- manifests/init.pp
- manifests/params.pp
- templates/killgpg.erb
This commit adds an option to allow a user to set max ttl and cache ttl
for gpg agent used for zpr offsite backups. Additionally, a job is added
to kill the gpg agent on Sundays at 5pm. This is not currently
configurable, but can be made configurable if needed. This change
ensures that the gpg agent is started each week. Without this change the
agent dies after a few weeks and stops working.
> Make ttl for gpg agent configurable and add kill script

- manifests/rsync.pp
- manifests/rsync_cmd.pp
- templates/rsync.erb
- templates/run_backup.erb
- templates/ssh_forced_commands_wrapper.py.erb
This commit updates rsync to use a template for the file resource,
instead of crafting the file from puppet based on variables. This
greatly simplifies the rsync command define type. In order to be
compatible with this method some minor updates to the ssh forced
commands wrapper were necessary and are included here.
Additionally, a check is performed before a backup job is started that
ensures the target volume is mounted over nfs.
> Restructure rsync cron command

- manifests/gpg.pp
This commit adds minute to the cron job that kills the gpg agent weekly. Without this change it runs every minute for that hour.
> Add minute to kill gpg

- templates/run_backup.erb
This commit adds a lockfile mechanism when running backup jobs. Without
this change it is possible for two backup jobs to run at the same time
without awareness of each other. The lockfile is implemented on a per
volume basis, and removed upon completion or termination of the job.
> Add a lock file mechanism to run_backup

- templates/run_backup.erb
- templates/ssh_forced_commands_wrapper.py.erb
This commit updates the zpr forced commands wrapper used for rsync
backups to support python 2.6. Without this change backups fail for
squeeze hosts. Additionally, the checking against a list of static
commands is simplified in order to support the ignore errors flag.
Without this change when ignore errors is set the job fails.
Lastly, the run_backup script used to start a rsync backup job is
updated to remove the lock file on exit. When this is not set and a job
exits due to a failure in the wrapper script, or triggering exit, a
lockfile is left over.
> Update forced commands to support python 2.6

- manifests/duplicity.pp
- manifests/init.pp
- manifests/lockfile_progs.pp
- manifests/offsite.pp
- manifests/params.pp
- manifests/rsync.pp
- manifests/worker.pp
This commit adds a timestamp to rsync jobs so they have a timestamp that
can be queried when queued. Without this change there is no way to
determine the time an item enters the queue.
Additionally, this adds a lockfile_progs class and includes it on worker
and offsite roles.
> Add a timestamp to backup job when queued

- templates/run_backup.erb
Without this change when running a job that exits due to a lock file the
lock file is removed upon exit. This commit corrects that behavior.
Additionally, error messages are sent to stderr.
> Improve run backup by only removing lock on exit if exit code is not 3.

- lib/facter/zpr_ssh_key.rb
This commit updates the zpr_ssh_pubkey fact to verify the user is
present before checking if the key exists. Without this change a ruby
error is printed when facter is run due to getpwent not finding the
zpr_proxy user.
> Update zpr ssh pubkey fact to check user first

- manifests/rsync.pp
This commit escapes the % in the date portion of the rsync command. Without this change the % generates an error and the command fails.
> Escape % in rsync cmd

- lib/facter/zpr_ssh_key.rb
This commit updates the zpr ssh pubkey fact to catch failure when the
zpr_proxy doesn't exist. Prior to this change I attempted to check id -u
with system which produces the UID when the user does exist. Instead,
this catches the exception when the user does not exist.
> Update zpr_ssh_pubkey fact to catch exception

- manifests/job.pp
This commit updates zpr to fail when a backup job title includes =. Without this change if a user creates a backup resource with = in the title it cannot be created and fails.
> Update zpr job to fail when resource title contains =

- manifests/duplicity.pp
- manifests/rsync.pp
This commit updates the placement of a timestamp in the command passed
to task spooler for duplicity and rsync jobs. Specifically, the command
is moved to the first command executed rather than the last. Without
this change the exit code of the time=$date command printed is returned
by task spooler instead of the exit code of the job.
> Update usage of timestamp in tsp command

- manifests/job.pp
This commit updates the backup job filter to catch commas when present. Without this change a backup job can be created with a comma which is not supported
> Prevent backup jobs with comma

- manifests/job.pp
This commit adds a check for a commercial at sign in a zpr job title. Without this change a user can create a job including the commercial at sign which is not supported by zfs.
> Check for commercial at sign in job title

- manifests/job.pp
This commit updates zpr::job to make zfs::snapshot utilize the keep parameter available in zpr::job. Without this change keep is always set to the zfs module default because the parameter is not passed through to the define type declaration in zpr::job.
> Update zfs::snapshot to specify keep

- manifests/user.pp
This commit updates the user class to set host key name by certname instead of fqdn. Without this change zpr cannot handle cases where there is a duplicate fqdn.
> Configure zpr user to generate uniquely titled keys
